Instagram/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
    resources :posts do
    resources :comments
  end
  root  'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Instagram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Instagram/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

Instagram/app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_many :comments, dependent: :destroy
end

Instagram/app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

Instagram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Instagram/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

def create
  @comment = @post.comments.build(comment_params)
  @comment.user_id = current_user.id
  if @comment.save
    flash[:success] = "You have successfully commented....I hope it was worth it"
    redirect_to root_path
  else
    flash[:alert] = "You failed to comment. Failed, I say"
    render root_path
  end
end

def destroy
  @comment = @post.comments.find(params[:id])
  @comment.destroy
  flash[:success] = "Comment deleted!"
  redirect_to root_path
end

private

def comment_params
  params.require(:comment).permit(:content)
end

def set_post
  @post = Post.find(params[:post_id])
end

end

Instagram/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :own_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(params_for_post)
      if @post.save
        flash[:success] = 'Your post has been uploaded! Congratulations!'
        redirect_to posts_path
      else
        flash[:alert] = 'Stop! You have to upload an image!'
        render :new
      end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params_for_post)
    redirect_to(params.require(:post).permit(:caption))
    flash[:success] = 'Your post has been updated!'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
    flash[:success] = 'Post deleted! No one needs to know'
  end


  private

  def own_post
    @post = Post.find(params[:id])
    unless current_user == @post.user
      flash[:alert] = "Go away, this is not your post"
      redirect_to root_path
    end
  end

  def params_for_post
    params.require(:post).permit(:caption, :image)
    # simply what parameters are permitted, in this case, the params are caption and image
  end

end

Instagram/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

Instagram/app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end  

Instagram/app/helpers/comments_helper.rb
module CommentsHelper
end

Instagram/app/helpers/posts_helper.rb
module PostsHelper
end

Instagram/app/views/comments/_comment.html.haml
#comment
  .user-name
    = comment.user.user_name
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do
      %span(class="glyphicon glyphicon-remove delete-comment")

Instagram/app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "InstaClone", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "New Post", new_post_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          Please log in or register
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

Instagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
<% end %>
</html>

Instagram/app/views/posts/edit.html.haml
= simple_form_for @post do |f|
  = f.input :caption
  = f.button :submit
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }

Instagram/app/views/posts/index.html.haml
.posts-wrapper.row
  -@posts.each do |post|
    .post
      .post-head
        .postedby
          =post.user.user_name
          posted this!
      .image.center-block
        =link_to (image_tag post.image.url(:medium)), post_path(post)
        %br/
        =post.caption
        %br/
        - if post.comments
          - post.comments.each do |comment|
            .comment
              .user-name
                = comment.user.user_name
                =':'
                = comment.content
        .comment-form
          = form_for [post, post.comments.new] do |f|
            = f.text_field :content, id:"submit_comment", placeholder: 'Comment...'
            = f.button :Submit

Instagram/app/views/posts/new.html.haml
= simple_form_for @post do |f|
  = f.input :image
  = f.input :caption
  = f.button :submit

Instagram/app/views/posts/show.html.haml
%h1 a nice individual view
= image_tag @post.image.url(:medium)
= @post.caption
- if current_user == @post.user
  = link_to "Edit", edit_post_path
- else
  %br
  you can't edit this